In [ ]:
#)***************************************************name: sudharsan J************************************
#)***************************************************course: datascience**********************************
#)***************************************************batch: d101******************************************
#)***************************************************topic:sql********************************************
# ***************************************************subtopic:innner merge/unique identifier in sql*******
#) short description: table 1(index=1395), table 2(index = 5479), after merge (index=5433):

In [ ]:
# importing comment details table
import pandas as pd
import simple_colors
df = pd.read_csv(r"D:\Sudharsan\Guvi_Data science\DS101_Sudharsan\Mainboot camp\capstone project\youtube_harvest\comment_details.csv")

# to know the columns of comment_details dataframe
df.columns

# to drop id column in the comment_details dataframe
df_comment_temp = df.drop(['_id'], axis=1)
df_comment_temp

# to check the id column dropped or not
df_comment_temp.columns

import mysql.connector
# establishing the connection between jupyter notebook and mysql
connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='Rudra@014',
    database = 'D101'
)
cursor = connection.cursor()

# creating table comments in sql
#query = """create table comments (corrosponding_channel_name varchar(100), comments_video varchar(250),comments_id varchar(300),
#        comments_text varchar(10000), comments_authors varchar(200),commented_date varchar(200))"""
#cursor.execute(query)

# inserting the comment_details data frame to comments table 
#query = "insert into comments values(%s,%s,%s,%s,%s,%s)"
#data_points = []
#for index in df_comment_temp.index:
#    row = df_comment_temp.loc[index].values
#    row = tuple([str(d) for d in row])
#    data_points.append(row)
#cursor.executemany(query,data_points)
#connection.commit()

# showing the video table in sql
print(simple_colors.green("showing the video table in sql:"))
query ="select * from video"
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

# counting the video table
print(simple_colors.green("counting the video table:"))
query = "select count('video_id') from video"
cursor.execute(query)
for data in cursor.fetchall():
    print(data)

# showing the comments table in sql
print(simple_colors.green("showing the comments table in sql:"))
query ="select * from comments"
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

# counting the comments table
print(simple_colors.green("counting the comments table in sql:"))
query = "select count('comments_video') from comments" #)comments_video is video id
cursor.execute(query)
for data in cursor.fetchall():
    print(data)

# performing inner merge video table with comment table and converting into excel
print(simple_colors.green("performing inner merge video table with comment table and converting into excel:"))
from pymysql import*
import pandas.io.sql as sql
import xlwt
df_merge=sql.read_sql("select * from comments inner join video on comments.comments_video=video.video_id",connection)
df_merge
#df_merge.to_excel('ds.xlsx')